// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Prisma 7: a connection URL do Migrate (CLI) vive aqui, não no schema.
  // O runtime (PrismaClient) usa o driver adapter em src/lib/prisma.ts.
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
